
development:
 adapter: postgresql
 encoding: unicode
 database: myapp2
 pool: 5
 username: shaitan
 password: 123456

test:
 adapter: postgresql
 encoding: unicode
 database: myapp1
 pool: 5
 username: shaitan
 password: 123456